import React, { useState, useEffect } from 'react';
import { Mail, CreditCard, X, ExternalLink, Save, CheckCircle2, AlertCircle, RefreshCw, Send, Zap } from 'lucide-react';
import {
  getActiveProvider, setActiveProvider,
  getWeb3FormsConfig, saveWeb3FormsConfig, clearWeb3FormsConfig, isWeb3FormsConfigured,
  getEmailJSConfig, saveEmailJSConfig, clearEmailJSConfig, isEmailJSConfigured,
  sendBookingReceiptEmail,
  type EmailProvider,
} from '../services/emailService';
import type { Booking } from '../context/BookingContext';
import type { Room } from '../data/mockData';

// ─── Test mock booking ────────────────────────────────────────────────────────
const makeMockBooking = (email: string): Booking => ({
  id: 'VJR-TEST-001',
  room: {
    id: '1',
    name: 'Presidential Suite (Test)',
    slug: 'presidential-suite-test',
    description: 'Test booking for email system verification.',
    detailedDescription: 'This is a test booking generated by the admin integration panel.',
    price: 150000,
    rating: 4.9,
    reviewsCount: 12,
    images: [],
    amenities: ['Free Wi-Fi', 'Air Conditioning', 'Smart TV'],
    featured: true,
    view: 'Garden View',
    bedType: 'King Size',
    capacity: 2,
    size: 85,
  } as Room,
  checkIn: new Date().toISOString().split('T')[0],
  checkOut: new Date(Date.now() + 86400000 * 2).toISOString().split('T')[0],
  guests: 2,
  totalPrice: 300000,
  guestDetails: {
    fullName: 'La Villa Rielle — Test Admin',
    email,
    phone: '+237 679 554 114',
    paymentMethod: 'MTN_MOMO',
    paymentPhone: '+237 679 554 114',
  },
  status: 'CONFIRMED',
  createdAt: new Date().toISOString(),
  qrCodeValue: 'VJR-VERIFY-TEST-001',
});

// ─── Props ────────────────────────────────────────────────────────────────────
interface IntegrationsPanelProps {
  isOpen: boolean;
  onClose: () => void;
}

// ─── Status badge ─────────────────────────────────────────────────────────────
const StatusBadge = ({ configured }: { configured: boolean }) => (
  <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full border ml-2 ${
    configured
      ? 'bg-green-50 text-green-700 border-green-200'
      : 'bg-amber-50 text-amber-700 border-amber-200'
  }`}>
    {configured ? '✓ Active' : 'Not Set'}
  </span>
);

// ─────────────────────────────────────────────────────────────────────────────
export const IntegrationsPanel: React.FC<IntegrationsPanelProps> = ({ isOpen, onClose }) => {

  type Tab = 'web3forms' | 'emailjs' | 'payment';
  const [activeTab, setActiveTab]   = useState<Tab>('web3forms');
  const [provider, setProvider]     = useState<EmailProvider>(getActiveProvider());

  // Web3Forms state
  const [w3Key,   setW3Key]         = useState('');
  const [w3Email, setW3Email]       = useState('');
  const [w3Saved, setW3Saved]       = useState(false);

  // EmailJS state
  const [ejsServiceId,  setEjsServiceId]  = useState('');
  const [ejsTemplateId, setEjsTemplateId] = useState('');
  const [ejsPublicKey,  setEjsPublicKey]  = useState('');
  const [ejsSaved,      setEjsSaved]      = useState(false);

  // Payment state
  const [paymentMode, setPaymentMode] = useState<'SIMULATED' | 'LIVE_NOTCHPAY' | 'LIVE_CAMPAY'>('SIMULATED');
  const [notchKey,    setNotchKey]    = useState('');
  const [campayId,    setCampayId]    = useState('');
  const [paySaved,    setPaySaved]    = useState(false);

  // Test email
  const [testEmail,    setTestEmail]   = useState('');
  const [testSending,  setTestSending] = useState(false);
  const [testResult,   setTestResult]  = useState<{ success: boolean; message: string } | null>(null);

  // Hydrate from storage when panel opens
  useEffect(() => {
    if (!isOpen) return;
    const w3 = getWeb3FormsConfig();
    setW3Key(w3.accessKey || '');
    setW3Email(w3.toEmail || '');

    const ejs = getEmailJSConfig();
    setEjsServiceId(ejs.serviceId || '');
    setEjsTemplateId(ejs.templateId || '');
    setEjsPublicKey(ejs.publicKey || '');

    setProvider(getActiveProvider());
    setPaymentMode((localStorage.getItem('vjr_payment_mode') as any) || 'SIMULATED');
    setNotchKey(localStorage.getItem('vjr_notch_key') || '');
    setCampayId(localStorage.getItem('vjr_campay_id') || '');
  }, [isOpen]);

  if (!isOpen) return null;

  // ── Helpers ──────────────────────────────────────────────────────────────────
  const flash = (setter: React.Dispatch<React.SetStateAction<boolean>>) => {
    setter(true);
    setTimeout(() => setter(false), 3000);
  };

  const handleSaveW3 = (e: React.FormEvent) => {
    e.preventDefault();
    saveWeb3FormsConfig({ accessKey: w3Key.trim(), toEmail: w3Email.trim() });
    setActiveProvider('WEB3FORMS');
    setProvider('WEB3FORMS');
    flash(setW3Saved);
  };

  const handleSaveEJS = (e: React.FormEvent) => {
    e.preventDefault();
    saveEmailJSConfig({ serviceId: ejsServiceId.trim(), templateId: ejsTemplateId.trim(), publicKey: ejsPublicKey.trim() });
    if (provider !== 'WEB3FORMS') {
      setActiveProvider('EMAILJS');
      setProvider('EMAILJS');
    }
    flash(setEjsSaved);
  };

  const handleSavePay = (e: React.FormEvent) => {
    e.preventDefault();
    localStorage.setItem('vjr_payment_mode', paymentMode);
    localStorage.setItem('vjr_notch_key', notchKey);
    localStorage.setItem('vjr_campay_id', campayId);
    flash(setPaySaved);
  };

  const handleClearW3 = () => {
    clearWeb3FormsConfig();
    setW3Key(''); setW3Email('');
    if (provider === 'WEB3FORMS') { setActiveProvider('NONE'); setProvider('NONE'); }
    flash(setW3Saved);
  };

  const handleClearEJS = () => {
    clearEmailJSConfig();
    setEjsServiceId(''); setEjsTemplateId(''); setEjsPublicKey('');
    if (provider === 'EMAILJS') { setActiveProvider('NONE'); setProvider('NONE'); }
    flash(setEjsSaved);
  };

  const handleTest = async () => {
    if (!testEmail) return;
    setTestSending(true);
    setTestResult(null);
    const result = await sendBookingReceiptEmail(makeMockBooking(testEmail));
    setTestSending(false);
    setTestResult({ success: result.success, message: result.message });
  };

  // ── Derived flags ─────────────────────────────────────────────────────────────
  const w3Configured  = isWeb3FormsConfigured({ accessKey: w3Key });
  const ejsConfigured = isEmailJSConfigured({ serviceId: ejsServiceId, templateId: ejsTemplateId, publicKey: ejsPublicKey });
  const anyConfigured = isWeb3FormsConfigured() || isEmailJSConfigured();

  // ── Tabs definition ────────────────────────────────────────────────────────────
  const tabs: { key: Tab; label: string; icon: React.ReactNode }[] = [
    { key: 'web3forms', label: 'Web3Forms',     icon: <Zap className="w-3.5 h-3.5" /> },
    { key: 'emailjs',   label: 'EmailJS',        icon: <Mail className="w-3.5 h-3.5" /> },
    { key: 'payment',   label: 'Payments',       icon: <CreditCard className="w-3.5 h-3.5" /> },
  ];

  // ─── RENDER ──────────────────────────────────────────────────────────────────
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-charcoal/60 backdrop-blur-sm overflow-y-auto">
      <div className="relative bg-cream-light border border-gold/20 rounded-3xl w-full max-w-2xl shadow-2xl overflow-hidden">

        {/* ── Header ── */}
        <div className="bg-charcoal px-6 py-5 flex items-center justify-between border-b border-gold/15">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-gold/15 border border-gold/30 rounded-xl">
              <Zap className="w-5 h-5 text-gold" />
            </div>
            <div>
              <h2 className="font-serif text-xl font-semibold text-cream-light tracking-wide">
                Automated System Config
              </h2>
              <p className="text-[11px] text-cream-dark/50 mt-0.5">
                Active provider:&nbsp;
                <span className={`font-bold ${provider === 'NONE' ? 'text-amber-400' : 'text-green-400'}`}>
                  {provider === 'WEB3FORMS' ? 'Web3Forms ✓' : provider === 'EMAILJS' ? 'EmailJS ✓' : 'None (Simulation)'}
                </span>
              </p>
            </div>
          </div>
          <button onClick={onClose} className="text-cream-dark/60 hover:text-cream-light p-1.5 rounded-full hover:bg-white/10 transition-colors">
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* ── Tab Bar ── */}
        <div className="flex border-b border-gold/10 bg-cream">
          {tabs.map(t => (
            <button
              key={t.key}
              onClick={() => setActiveTab(t.key)}
              className={`flex-1 py-3 text-xs font-bold flex items-center justify-center gap-1.5 border-b-2 transition-all ${
                activeTab === t.key
                  ? 'border-gold text-gold bg-gold/5'
                  : 'border-transparent text-charcoal-light hover:text-gold hover:bg-gold/5'
              }`}
            >
              {t.icon} {t.label}
              {t.key === 'web3forms' && <StatusBadge configured={isWeb3FormsConfigured()} />}
              {t.key === 'emailjs'   && <StatusBadge configured={isEmailJSConfigured()} />}
            </button>
          ))}
        </div>

        {/* ── Tab Content ── */}
        <div className="p-6 overflow-y-auto max-h-[65vh] space-y-5">

          {/* ════════════════════════ WEB3FORMS TAB ════════════════════════ */}
          {activeTab === 'web3forms' && (
            <>
              {/* Recommendation banner */}
              <div className="flex items-start gap-3 p-4 bg-gold/8 border border-gold/20 rounded-2xl">
                <Zap className="w-5 h-5 text-gold shrink-0 mt-0.5" />
                <div>
                  <p className="text-sm font-bold text-charcoal">Recommended Provider</p>
                  <p className="text-xs text-charcoal-light mt-0.5 leading-relaxed">
                    Web3Forms is the easiest way to receive booking receipts — no backend needed.
                    Just paste your <strong>Access Key</strong> and receipts land directly in your inbox.
                    Free plan: <strong>250 emails/month</strong>.
                  </p>
                  <a href="https://web3forms.com" target="_blank" rel="noreferrer"
                     className="text-[11px] text-gold font-semibold hover:underline inline-flex items-center gap-1 mt-1">
                    Get your free key at web3forms.com <ExternalLink className="w-3 h-3" />
                  </a>
                </div>
              </div>

              {/* Status indicator */}
              <div className={`p-3.5 rounded-2xl flex items-center gap-3 border ${
                isWeb3FormsConfigured()
                  ? 'bg-green-50 border-green-200 text-green-800'
                  : 'bg-amber-50 border-amber-200 text-amber-800'
              }`}>
                {isWeb3FormsConfigured() ? (
                  <><CheckCircle2 className="w-5 h-5 text-green-600 shrink-0" />
                  <div>
                    <p className="text-xs font-bold">Web3Forms Active — Receipts are being sent automatically</p>
                    <p className="text-[10px] opacity-80">Emails route directly to your configured inbox on every confirmed booking.</p>
                  </div></>
                ) : (
                  <><AlertCircle className="w-5 h-5 text-amber-600 shrink-0" />
                  <div>
                    <p className="text-xs font-bold">Web3Forms Not Configured</p>
                    <p className="text-[10px] opacity-80">Enter your Access Key below to enable instant automated receipts.</p>
                  </div></>
                )}
              </div>

              {/* Form */}
              <form onSubmit={handleSaveW3} className="space-y-3">
                <div className="flex flex-col gap-1.5">
                  <label className="text-[10px] text-sage font-bold uppercase tracking-wider">
                    Access Key <span className="text-gold">*</span>
                  </label>
                  <input
                    type="text" required
                    placeholder="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
                    value={w3Key}
                    onChange={e => setW3Key(e.target.value)}
                    className="border border-gold/20 rounded-xl px-4 py-2.5 text-sm focus:outline-none focus:border-gold bg-cream font-mono"
                  />
                  <p className="text-[10px] text-charcoal-light">
                    Find this in your Web3Forms dashboard under <em>Settings → Access Key</em>.
                  </p>
                </div>

                <div className="flex flex-col gap-1.5">
                  <label className="text-[10px] text-sage font-bold uppercase tracking-wider">
                    Route receipts to (optional override)
                  </label>
                  <input
                    type="email"
                    placeholder="reservations@lavillarielle.com"
                    value={w3Email}
                    onChange={e => setW3Email(e.target.value)}
                    className="border border-gold/20 rounded-xl px-4 py-2.5 text-sm focus:outline-none focus:border-gold bg-cream"
                  />
                  <p className="text-[10px] text-charcoal-light">
                    Leave blank to use the email linked to your Web3Forms account.
                  </p>
                </div>

                <div className="flex gap-2 pt-1">
                  <button type="submit"
                    className="flex-1 bg-gold hover:bg-gold-dark text-cream-light py-2.5 rounded-xl font-bold text-sm transition-all shadow flex items-center justify-center gap-2">
                    <Save className="w-4 h-4" /> Save & Activate
                  </button>
                  {isWeb3FormsConfigured() && (
                    <button type="button" onClick={handleClearW3}
                      className="border border-red-200 text-red-600 hover:bg-red-50 px-4 py-2.5 rounded-xl text-sm font-medium transition-all">
                      Clear
                    </button>
                  )}
                </div>

                {w3Saved && (
                  <p className="text-xs text-green-600 font-semibold text-center animate-pulse">✓ Web3Forms credentials saved!</p>
                )}
              </form>

              {/* How it works */}
              <div className="bg-charcoal rounded-2xl p-5 text-xs text-cream-dark/80 space-y-1.5 border border-gold/10">
                <p className="font-bold text-gold text-[10px] uppercase tracking-widest mb-2">Quick Setup (2 minutes)</p>
                <ol className="list-decimal pl-4 space-y-1.5 leading-relaxed">
                  <li>Go to <a href="https://web3forms.com" target="_blank" rel="noreferrer" className="text-gold hover:underline">web3forms.com</a> and click <strong>Get your Access Key for free</strong>.</li>
                  <li>Enter your email — your Access Key will be emailed to you instantly.</li>
                  <li>Paste the key above and click <strong>Save & Activate</strong>.</li>
                  <li>Use the <strong>Test Receipt</strong> section below to confirm it's working.</li>
                </ol>
              </div>

              {/* Test section */}
              {anyConfigured && (
                <div className="bg-cream border border-gold/15 rounded-2xl p-5 space-y-3">
                  <h3 className="text-sm font-bold text-charcoal flex items-center gap-2">
                    <Send className="w-4 h-4 text-gold" /> Send Test Receipt Now
                  </h3>
                  <div className="flex gap-2">
                    <input type="email" placeholder="your@email.com" value={testEmail}
                      onChange={e => setTestEmail(e.target.value)}
                      className="flex-1 border border-gold/20 rounded-xl px-4 py-2 text-sm focus:outline-none focus:border-gold bg-cream-light" />
                    <button onClick={handleTest} disabled={testSending || !testEmail}
                      className="bg-charcoal hover:bg-charcoal-dark text-cream-light px-4 py-2 rounded-xl font-bold text-xs transition-all shadow disabled:opacity-50 flex items-center gap-1.5">
                      {testSending ? <RefreshCw className="w-3.5 h-3.5 animate-spin" /> : <Send className="w-3.5 h-3.5" />}
                      Send Test
                    </button>
                  </div>
                  {testResult && (
                    <p className={`text-xs font-semibold ${testResult.success ? 'text-green-600' : 'text-red-500'}`}>
                      {testResult.success ? '✓' : '✗'} {testResult.message}
                    </p>
                  )}
                </div>
              )}
            </>
          )}

          {/* ════════════════════════ EMAILJS TAB ════════════════════════ */}
          {activeTab === 'emailjs' && (
            <>
              <div className="p-4 bg-charcoal/5 border border-gold/10 rounded-2xl text-xs text-charcoal-light leading-relaxed">
                <p className="font-bold text-charcoal mb-1">EmailJS — Alternative Provider</p>
                EmailJS lets you send emails from custom HTML templates. Useful if you need fine-grained control over the email design.
                Free plan: <strong>200 emails/month</strong>. &nbsp;
                <a href="https://www.emailjs.com" target="_blank" rel="noreferrer" className="text-gold font-semibold hover:underline inline-flex items-center gap-0.5">
                  emailjs.com <ExternalLink className="w-3 h-3" />
                </a>
              </div>

              {/* Status */}
              <div className={`p-3.5 rounded-2xl flex items-center gap-3 border ${
                isEmailJSConfigured()
                  ? 'bg-green-50 border-green-200 text-green-800'
                  : 'bg-amber-50 border-amber-200 text-amber-800'
              }`}>
                {isEmailJSConfigured() ? (
                  <><CheckCircle2 className="w-5 h-5 text-green-600 shrink-0" />
                  <p className="text-xs font-bold">EmailJS is configured and ready to send.</p></>
                ) : (
                  <><AlertCircle className="w-5 h-5 text-amber-600 shrink-0" />
                  <p className="text-xs font-bold">EmailJS credentials not yet entered.</p></>
                )}
              </div>

              <form onSubmit={handleSaveEJS} className="space-y-3">
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  <div className="flex flex-col gap-1.5">
                    <label className="text-[10px] text-sage font-bold uppercase tracking-wider">Service ID *</label>
                    <input type="text" required placeholder="service_xxxxxxx" value={ejsServiceId}
                      onChange={e => setEjsServiceId(e.target.value)}
                      className="border border-gold/20 rounded-xl px-4 py-2.5 text-sm focus:outline-none focus:border-gold bg-cream font-mono" />
                  </div>
                  <div className="flex flex-col gap-1.5">
                    <label className="text-[10px] text-sage font-bold uppercase tracking-wider">Template ID *</label>
                    <input type="text" required placeholder="template_xxxxxxx" value={ejsTemplateId}
                      onChange={e => setEjsTemplateId(e.target.value)}
                      className="border border-gold/20 rounded-xl px-4 py-2.5 text-sm focus:outline-none focus:border-gold bg-cream font-mono" />
                  </div>
                </div>
                <div className="flex flex-col gap-1.5">
                  <label className="text-[10px] text-sage font-bold uppercase tracking-wider">Public Key *</label>
                  <input type="text" required placeholder="YOUR_PUBLIC_KEY" value={ejsPublicKey}
                    onChange={e => setEjsPublicKey(e.target.value)}
                    className="border border-gold/20 rounded-xl px-4 py-2.5 text-sm focus:outline-none focus:border-gold bg-cream font-mono" />
                </div>

                {/* Template variable reference */}
                <div className="bg-cream border border-gold/10 rounded-xl p-3.5 text-[10px] text-charcoal-light">
                  <p className="font-bold text-charcoal mb-1.5">Template variables to add in EmailJS:</p>
                  <div className="grid grid-cols-2 sm:grid-cols-3 gap-x-3 gap-y-1 font-mono text-sage">
                    {['{{booking_id}}','{{guest_name}}','{{guest_email}}','{{guest_phone}}','{{room_name}}',
                      '{{check_in}}','{{check_out}}','{{guests}}','{{total_price}}','{{payment_method}}',
                      '{{payment_phone}}','{{created_at}}'].map(v => (
                      <span key={v}>{v}</span>
                    ))}
                  </div>
                </div>

                <div className="flex gap-2 pt-1">
                  <button type="submit"
                    className="flex-1 bg-gold hover:bg-gold-dark text-cream-light py-2.5 rounded-xl font-bold text-sm transition-all shadow flex items-center justify-center gap-2">
                    <Save className="w-4 h-4" /> Save EmailJS Config
                  </button>
                  {isEmailJSConfigured() && (
                    <button type="button" onClick={handleClearEJS}
                      className="border border-red-200 text-red-600 hover:bg-red-50 px-4 py-2.5 rounded-xl text-sm font-medium transition-all">
                      Clear
                    </button>
                  )}
                </div>
                {ejsSaved && <p className="text-xs text-green-600 font-semibold text-center animate-pulse">✓ EmailJS credentials saved!</p>}
              </form>

              {/* Test */}
              {anyConfigured && (
                <div className="bg-cream border border-gold/15 rounded-2xl p-5 space-y-3">
                  <h3 className="text-sm font-bold text-charcoal flex items-center gap-2">
                    <Send className="w-4 h-4 text-gold" /> Send Test Receipt
                  </h3>
                  <div className="flex gap-2">
                    <input type="email" placeholder="your@email.com" value={testEmail}
                      onChange={e => setTestEmail(e.target.value)}
                      className="flex-1 border border-gold/20 rounded-xl px-4 py-2 text-sm focus:outline-none focus:border-gold bg-cream-light" />
                    <button onClick={handleTest} disabled={testSending || !testEmail}
                      className="bg-charcoal hover:bg-charcoal-dark text-cream-light px-4 py-2 rounded-xl font-bold text-xs transition-all shadow disabled:opacity-50 flex items-center gap-1.5">
                      {testSending ? <RefreshCw className="w-3.5 h-3.5 animate-spin" /> : <Send className="w-3.5 h-3.5" />}
                      Send Test
                    </button>
                  </div>
                  {testResult && (
                    <p className={`text-xs font-semibold ${testResult.success ? 'text-green-600' : 'text-red-500'}`}>
                      {testResult.success ? '✓' : '✗'} {testResult.message}
                    </p>
                  )}
                </div>
              )}
            </>
          )}

          {/* ════════════════════════ PAYMENT TAB ════════════════════════ */}
          {activeTab === 'payment' && (
            <>
              <div className="p-4 bg-gold/5 border border-gold/15 rounded-2xl">
                <p className="text-sm font-bold text-charcoal mb-1">Cameroon Mobile Money — Automated Collections</p>
                <p className="text-xs text-charcoal-light leading-relaxed">
                  Connect a payment aggregator to collect MTN Mobile Money and Orange Money automatically.
                  When a guest pays, the aggregator sends a webhook to confirm the transaction — triggering
                  the booking confirmation and receipt email automatically.
                </p>
              </div>

              <form onSubmit={handleSavePay} className="space-y-4">
                <div className="flex flex-col gap-1.5">
                  <label className="text-[10px] text-sage font-bold uppercase tracking-wider">Payment Mode</label>
                  <select value={paymentMode} onChange={e => setPaymentMode(e.target.value as any)}
                    className="border border-gold/20 rounded-xl px-4 py-2.5 text-sm focus:outline-none focus:border-gold bg-cream">
                    <option value="SIMULATED">Simulated (Demo — for testing only)</option>
                    <option value="LIVE_NOTCHPAY">Live — Notch Pay Integration</option>
                    <option value="LIVE_CAMPAY">Live — Campay Integration</option>
                  </select>
                </div>

                {paymentMode === 'LIVE_NOTCHPAY' && (
                  <div className="p-4 bg-cream border border-gold/15 rounded-2xl space-y-2">
                    <label className="text-[10px] text-sage font-bold uppercase tracking-wider block">Notch Pay Public Key *</label>
                    <input type="text" required placeholder="pk_live_xxxxxxxxxxxxxxxx" value={notchKey}
                      onChange={e => setNotchKey(e.target.value)}
                      className="w-full border border-gold/20 rounded-xl px-4 py-2.5 text-sm focus:outline-none focus:border-gold bg-cream-light font-mono" />
                    <p className="text-[10px] text-charcoal-light">
                      Get your key from your&nbsp;
                      <a href="https://business.notchpay.co/developer/api-keys" target="_blank" rel="noreferrer" className="text-gold hover:underline inline-flex items-center gap-0.5">
                        Notch Pay dashboard <ExternalLink className="w-3 h-3" />
                      </a>.
                    </p>
                  </div>
                )}

                {paymentMode === 'LIVE_CAMPAY' && (
                  <div className="p-4 bg-cream border border-gold/15 rounded-2xl space-y-2">
                    <label className="text-[10px] text-sage font-bold uppercase tracking-wider block">Campay App Token *</label>
                    <input type="text" required placeholder="app_xxxxxxxxxxxxxxxx" value={campayId}
                      onChange={e => setCampayId(e.target.value)}
                      className="w-full border border-gold/20 rounded-xl px-4 py-2.5 text-sm focus:outline-none focus:border-gold bg-cream-light font-mono" />
                    <p className="text-[10px] text-charcoal-light">
                      Get your token from your&nbsp;
                      <a href="https://www.campay.net" target="_blank" rel="noreferrer" className="text-gold hover:underline inline-flex items-center gap-0.5">
                        Campay portal <ExternalLink className="w-3 h-3" />
                      </a>.
                    </p>
                  </div>
                )}

                <button type="submit"
                  className="w-full bg-gold hover:bg-gold-dark text-cream-light py-2.5 rounded-xl font-bold text-sm transition-all shadow flex items-center justify-center gap-2">
                  <Save className="w-4 h-4" /> Save Payment Settings
                </button>
                {paySaved && <p className="text-xs text-green-600 font-semibold text-center animate-pulse">✓ Payment settings saved!</p>}
              </form>

              {/* Flow diagram */}
              <div className="bg-charcoal rounded-2xl p-5 border border-gold/10">
                <p className="text-[10px] font-bold text-gold uppercase tracking-widest mb-3">How automated payment → receipt works:</p>
                <div className="space-y-0">
                  {[
                    'Guest selects room & enters payment details',
                    'MTN/Orange Money push notification sent to guest phone',
                    'Guest approves on their phone',
                    'Payment provider confirms via webhook',
                    'Booking confirmed + receipt auto-emailed instantly ✓',
                  ].map((step, i) => (
                    <div key={i}>
                      <div className="flex items-center gap-3 text-[11px] text-cream-dark/80">
                        <span className={`w-5 h-5 rounded-full flex items-center justify-center text-[9px] font-bold shrink-0 ${
                          i === 4 ? 'bg-gold text-charcoal' : 'bg-cream-dark/10 text-cream-dark/60'
                        }`}>{i + 1}</span>
                        <span className={i === 4 ? 'text-gold font-bold' : ''}>{step}</span>
                      </div>
                      {i < 4 && <div className="w-px h-4 bg-cream-dark/10 ml-2.5" />}
                    </div>
                  ))}
                </div>
              </div>
            </>
          )}
        </div>

        {/* ── Footer ── */}
        <div className="bg-cream border-t border-gold/10 px-6 py-3 text-center">
          <p className="text-[10px] text-charcoal-light">
            <span className="font-semibold text-charcoal">La Villa Rielle</span> — Automated Booking System &nbsp;·&nbsp; All keys stored locally in your browser
          </p>
        </div>

      </div>
    </div>
  );
};
